export const ServerUrl = "http://localhost:8100";
export const WebServer = "http://localhost:8100";
export const MockServer = "http://127.0.0.1:8888";
export const SearchServer = "http://localhost:8100";
export const Api = {
    getUser: ServerUrl + "/user/:id",
    users: ServerUrl + "/users",
    userLogin: ServerUrl + "/user/auth",
    getWishListItems: ServerUrl + "/wishlist",
    getGame: ServerUrl + "/game/:id",
    games: ServerUrl + "/games",
    getCartList: ServerUrl + "/user/:id/carts",
    carts: ServerUrl + "/carts",
    cart: ServerUrl + "/cart/:id",
    getOrderList: ServerUrl + "/orders",
    payOrder: ServerUrl + "/order/:id/pay",
    order: ServerUrl + "/order/:id",
    orders: ServerUrl + "/orders",
    profile: ServerUrl + "/user/:id/profile",
    fetchGame: ServerUrl + "/game/:id",
    uploadUserAvatar: ServerUrl + "/user/:id/avatar/upload",
    fetchOrderGood: ServerUrl + "/ordergood",
    fetchGood: `${ServerUrl}/good/:id`,
    goods: `${ServerUrl}/goods`,
    deleteWishlistItems: `${ServerUrl}/wishlist`,
    wishlist: `${ServerUrl}/wishlist/:id`,
    inventors: `${ServerUrl}/inventoLrs`,
    comments: `${ServerUrl}/comments`,
    profileList: `${ServerUrl}/profile`,
    sendResetPasswordMail: `${ServerUrl}/user/reset`,
    resetPassword: `${ServerUrl}/user/password`,
    gameCommentSummary: `${ServerUrl}/game/:id/comments/summary`,
    comment: `${ServerUrl}/comment/:id`,
    userImventoryGame: `${ServerUrl}/user/:id/inventory/game`,
    userWallet: `${ServerUrl}/user/:id/wallet`,
    userTransactionList: `${ServerUrl}/user/:id/transactions`,
    gameCollections: `${ServerUrl}/collections`,
    searchGame: `${ServerUrl}/search`,
    settingIndexCollection:`${ServerUrl}/setting/index_collection`,
    goodSaleAna:`${ServerUrl}/goods/sale_ana`,
    tag:`${ServerUrl}/tag/:id`
};
